### PR TITLE
UI: add tooltip for buttons; float positioning for buttons

### PR DESCRIPTION
**Pull request by yfdyh000**
In addition, not understood the `span.context` in sidebar.css. Devtools is not efficient for dynamically generated elements.

### CODE REVIEW

**Comment by andymckay** [comment]
Thanks. I notice that if I reduce the width down, I lose the ones on the right which might be the most important one (close).

screenshot 2017-03-09 10 03 46

**Comment by andymckay** [comment]
That works great for me, sadly looks like there's a conflict.

**Comment by andymckay** [comment]
Oh wait, github lied to me.

**Comment by andymckay** [comment]
Thanks!

**Comment by yfdyh000** [comment]
updated. rebased.

Propose the min-width and max-width keys to block [bug 1208596](https://bugzilla.mozilla.org/show_bug.cgi?id=1208596)?

**Comment by andymckay** [comment]
A bug for forcing a min width is probably a good idea, let's block https://bugzilla.mozilla.org/show_bug.cgi?id=1329022 instead though.

**Pull request merged**
